---
- hosts: webservers
  tasks:
  - name: Loob allalaadimise kausta
    file:
     path=/root/allalaadimised
     owner=root
     group=root
     mode=0755
     state=directory

  - name: Laeb alla mysql paketi
    get_url:
      url: http://repo.mysql.com/mysql-apt-config_0.8.6-1_all.deb
      dest: "/root/allalaadimised"
      mode: 0440

  - name: Install mysql paki
    apt: "deb=/root/allalaadimised/mysql-apt-config_0.8.6-1_all.deb"

  - name: Install mysql
    apt: name=mysql-server state=present

  - name: Install python-mysqldb
    apt: name=python-mysqldb state=latest

  - name: Loome kasutaja
    mysql_user:
      name: root
      password: qwerty
      priv: '*.*:ALL,GRANT'
      state: present

  - name: root login
    copy:
      dest: /root/.my.cnf
      owner: root
      group: root
      mode: 0600
      content: |
           [client]
           user=root
           password=qwerty
  - name: Restart mysql
    service: name=mysql state=restarted
