---
- hosts: webservers
  tasks:
    - name: Installib php7.0
      apt: name=php7.0 update_cache=yes state=latest
    - name: Installib libapache-mod-php7.0
      apt: name=libapache2-mod-php7.0 update_cache=yes state=latest
    - name: Installib php7.0-mysql
      apt: name=php7.0-mysql update_cache=yes state=latest

    - name: Restart apache2
      service:
        name: apache2
        state: restarted
