---
- hosts: webservers
  tasks:

  - name: Andmebaas wordpressi jaoks
    mysql_db:
      name: wpdatabase
      state: present

  - name: Loob kasutaja
    mysql_user:
      name: wpuser
      password: qwerty
      priv: 'wpdatabase.*:ALL,GRANT'
      state: present
      check_implicit_admin: yes

  - name: Restart mysql
    service: name=mysql state=restarted

  - name: install wordpress
    unarchive:
      src: https://wordpress.org/latest.tar.gz
      dest: /var/www/html/
      remote_src: yes

  - name: wordpress kausta omanik
    file:
      path: /var/www/html/wordpress/
      state: directory
      recurse: yes
      owner: www-data

  - name: Copy config fail
    command: cp /var/www/html/wordpress/wp-config-sample.php /var/www/html/wordpress/wp-config.php

  - name: Muudab 'DB_PASSWORD'
    lineinfile: dest=/var/www/html/wordpress/wp-config.php regexp="password_here'" line="define( 'DB_PASSWORD', 'qwerty' );"

  - name: Muudab 'DB_USER'
    lineinfile: dest=/var/www/html/wordpress/wp-config.php regexp="username_here" line="define( 'DB_USER', 'andres' );"

  - name: Muudab 'DB_NAME'
    lineinfile: dest=/var/www/html/wordpress/wp-config.php regexp="database_name_here" line="define( 'DB_NAME', 'wordpress' );"
